
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq1Cp7pm2mBuJOYvghJy5Y4loHmLUGbEM',
    appId: '1:698814104515:web:4207390cf20e18c1f6f376',
    messagingSenderId: '698814104515',
    projectId: 'mynotes-qpp',
    authDomain: 'mynotes-qpp.firebaseapp.com',
    storageBucket: 'mynotes-qpp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD3ZiFojxoffUIweR_EV2NejebaPzT4Ks',
    appId: '1:698814104515:android:9baf5a285b5519b6f6f376',
    messagingSenderId: '698814104515',
    projectId: 'mynotes-qpp',
    storageBucket: 'mynotes-qpp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAleRcdQm_6GSpPYgVxNoWn3HLPz3aif0o',
    appId: '1:698814104515:ios:d30d6586df1b11daf6f376',
    messagingSenderId: '698814104515',
    projectId: 'mynotes-qpp',
    storageBucket: 'mynotes-qpp.appspot.com',
    iosBundleId: 'in.pixolity.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAleRcdQm_6GSpPYgVxNoWn3HLPz3aif0o',
    appId: '1:698814104515:ios:03d2ab551d33aca6f6f376',
    messagingSenderId: '698814104515',
    projectId: 'mynotes-qpp',
    storageBucket: 'mynotes-qpp.appspot.com',
    iosBundleId: 'in.pixolity.mynotes.RunnerTests',
  );
}
